import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import RecoidContextProvider from "@/atom/atom";
import Loading from "@/component/loading";

export const fzHbrGame = localFont({
  src: "./fonts/FzHBRGame.ttf",
  variable: "--font-fz-hbr-game",
  weight: "100 900",
});

export const utmCafeta = localFont({
  src: "./fonts/UTM_Cafeta.ttf",
  variable: "--font-utm-cafeta",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${utmCafeta.variable} ${fzHbrGame.variable}`} style={{ fontFamily: 'var(--font-utm-cafeta)' }}>
        <RecoidContextProvider>
          <Loading />
          {children}
        </RecoidContextProvider>
      </body>
    </html>
  );
}
